### PR TITLE
117 upgrade components to JUnit5

### PR DESCRIPTION
**Pull request by caldoe**

### CODE REVIEW

**Comment by Perevalov** [comment]
@caldoe Could you change the `annotatedBy` part of SPARQL query in SINA: https://github.com/caldoe/Qanary-question-answering-components/blob/472c041c0ffa18a87432f383fb3a02f3d4442f10/qanary-component-QB-Sina/src/main/java/eu/wdaqua/qanary/component/sina/qb/SINA.java#L252 to `<urn:qanary:" + spring.application.name + ">`, where `spring.application.name` you take from the `application.properties`?

**Comment by caldoe** [comment]
> @caldoe Could you change the `annotatedBy` part of SPARQL query in SINA: https://github.com/caldoe/Qanary-question-answering-components/blob/472c041c0ffa18a87432f383fb3a02f3d4442f10/qanary-component-QB-Sina/src/main/java/eu/wdaqua/qanary/component/sina/qb/SINA.java#L252 to `<urn:qanary:" + spring.application.name + ">`, where `spring.application.name` you take from the `application.properties`?

done

**Comment by Perevalov** [comment]
@caldoe Thanks. One more change request. In the line https://github.com/caldoe/Qanary-question-answering-components/blob/472c041c0ffa18a87432f383fb3a02f3d4442f10/qanary-component-QB-Sina/src/main/java/eu/wdaqua/qanary/component/sina/qb/SINA.java#L222 please integrate the timeout variable in seconds (see [example](https://stackoverflow.com/questions/37043114/how-to-stop-a-command-being-executed-after-4-5-seconds-through-process-builder) -- `process.waitFor(5, TimeUnit.SECONDS);`). The timeout should be specified in the `application.properties` with the default value of 5 seconds.

**Comment by anbo-de** [comment]
@caldoe The tests for `qanary-component-QB-PlatypusWrapper` are not executable:

```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ qanary-component-QB-PlatypusWrapper ---
[INFO] Compiling 4 source files to Qanary-question-answering-components/qanary-component-QB-PlatypusWrapper/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Qanary-question-answering-components/qanary-component-QB-PlatypusWrapper/src/test/java/eu/wdaqua/qanary/component/platypuswrapper/qb/MockPlatypusQueryBuilderTest.java:[77,9] cannot find symbol
  symbol:   method assertEquals(java.lang.String,java.lang.String)
  location: class eu.wdaqua.qanary.component.platypuswrapper.qb.MockPlatypusQueryBuilderTest
[ERROR] Qanary-question-answering-components/qanary-component-QB-PlatypusWrapper/src/test/java/eu/wdaqua/qanary/component/platypuswrapper/qb/MockPlatypusQueryBuilderTest.java:[89,9] cannot find symbol
  symbol:   method assertFalse(boolean)
  location: class eu.wdaqua.qanary.component.platypuswrapper.qb.MockPlatypusQueryBuilderTest
```
There seems to be missing imports. At least: 

```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
```

However, after adding the imports, there is another error. Is `mvn package` work for you on the whole repository?

**Comment by caldoe** [comment]
> However, after adding the imports, there is another error. Is `mvn package` work for you on the whole repository?

@anbo-de Unfortunately, due to the limitations of DockerHub, I can only run the entire build process once every 6 hours. Small errors keep occurring, such as forgotten imports, which do not occur when running the individual build processes. I am continuing to work on the problems.

**Comment by Perevalov** [comment]
> > @caldoe Thanks. One more change request. In the line https://github.com/caldoe/Qanary-question-answering-components/blob/472c041c0ffa18a87432f383fb3a02f3d4442f10/qanary-component-QB-Sina/src/main/java/eu/wdaqua/qanary/component/sina/qb/SINA.java#L222 please integrate the timeout variable in seconds (see [example](https://stackoverflow.com/questions/37043114/how-to-stop-a-command-being-executed-after-4-5-seconds-through-process-builder) -- `process.waitFor(5, TimeUnit.SECONDS);`). The timeout should be specified in the `application.properties` with the default value of 5 seconds.
> 
> @Perevalov done

@caldoe Unfortunately, that does not work in the situation when the process takes too long, for some reason the process never ends. I tried this code snippet instead:

```java
        if (!p.waitFor(processTimeout, TimeUnit.SECONDS)) {
            logger.warn("SINA JAR file execution timed out after {} seconds", processTimeout);
            p.destroy();
        }
```

but one of the tests fails. Could you try to check this problem, mainly, why the process is not stopped after the timeout?

Related stackoverflow question: https://stackoverflow.com/questions/1247390/java-native-process-timeout

**Comment by caldoe** [comment]
> Could you try to check this problem, mainly, why the process is not stopped after the timeout?

@Perevalov 
I think `waitFor` does not kill the process after the time elapsed, it only returns a status.
https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor-long-java.util.concurrent.TimeUnit-

I will check your snippet and the tests.

**Comment by anbo-de** [comment]
> > However, after adding the imports, there is another error. Is `mvn package` work for you on the whole repository?
> 
> @anbo-de Unfortunately, due to the limitations of DockerHub, I can only run the entire build process once every 6 hours. Small errors keep occurring, such as forgotten imports, which do not occur when running the individual build processes. I am continuing to work on the problems.

@caldoe You can use `mvn package -Ddockerfile.skip=true` to remove the dependency to Dockerhub and test the behavior without time limitations.

**Comment by anbo-de** [comment]
@caldoe Now, all components can be successfully built. Should I merge the pull request now?

**Comment by caldoe** [comment]
> @caldoe Now, all components can be successfully built. Should I merge the pull request now?

I'm still working on the SINA component. But I think we should open a Ticket for this, @Perevalov  shouldn't we?

**Comment by caldoe** [comment]
@Perevalov i added a new issue https://github.com/anbo-de/team-tasks/issues/130

**Comment by caldoe** [comment]
@anbo-de I think u can merge it now, we will solve the SINA problem in a new issue

**Comment by anbo-de** [comment]
@caldoe Keep up the excellent work!

**Pull request merged**
