### PR TITLE
167 components update

### PR DESCRIPTION
**Pull request by caldoe**
- [ASR Kaldi 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/commit/838f8b33203bf768e990ccd5c075153fe481fc43)  
- [CLS CLSNLIOD 4.1.5](https://github.com/WDAqua/Qanary-question-answering-components/commit/b43cba526f9b8e9514caa2fca48cd489891b064d) 
- [LD Shuyo 4.1.3](https://github.com/WDAqua/Qanary-question-answering-components/commit/58cc3f078bbc46b4ba76d40cd3ab5a4bfabb1a3e) 
- [NED AGDISTIS 4.1.4](https://github.com/WDAqua/Qanary-question-answering-components/commit/8484ffe2b1828cb7b6f3fc93e85b9a3b664633e6) 
- [NED-Ambiverse 3.1.4](https://github.com/WDAqua/Qanary-question-answering-components/commit/cc19103131f574f7a67c6b2e3fb1ab099fded27a) 
- [NED-Aylien 4.1.5](https://github.com/WDAqua/Qanary-question-answering-components/commit/d94f3758b46afa5f66f91ac9b2a67fe03616025c) 
- [NED-Babelfy 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/commit/f0cad9f75c582cdfaa5788b3e2f8d5cc8e29799e)
- [NED-Dandelion 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/88c4ca477d9dd7cc0209ef3fdc074eccf593a2de) 
- [NED-DBpediaSpotlight 3.2.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/5e09abd1c76d3a0e5bcf91e072c91900131143a9) 
- [NED-DBpediaSpotlight 3.2.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/4c2ee925e8d25b5d1c9c93061d9eb0c1d7953f3c) 
- [NED DiambiguationClass OKBQA 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/dee2d507b3fec03873b5793592a98de68761aecd)
- [Merge branch 'master' into 167_components_update](https://github.com/WDAqua/Qanary-question-answering-components/commit/9d686d9988a375e858f87f23a210f1a5e1e8fd3d)

**UPDATE**

- [NED MeaningCloud 3.0.6](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/ac70dedaf79fd1b8d45ea3140e52a5f644cea229)
- [NED Ontotext 3.0.3](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/07bfec59991149cd10cbb2963f5c51afddf74949) 
- [NED Opentapioca 3.2.1](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/2bea64e4dae8dc571eb0f3524bd03736f8a3cb8e) 
- [NED Tagme 3.1,4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/504f39cc56b6e7bfebfc34551a7c67bf82521fe0) 
- [NED Watson 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/5366738bb7277c67b09466ce7f20abcc37097937) 
- [NED Tagme 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/2366a9d678429ee24d2dc5c707bb308e28061dc5)
- [Merge remote-tracking branch 'origin/167_components_update' into 167_…](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/2cf6838cf7848c8bab4a799779bc4a92809c57d5)
- [NER-Ambiverse 3.1.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/35f7cd8053c53896932ecf184ff1cb61d1b31424) 
- [NER-Aylien 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/b2110e941a8344aab9c3f10b0862ff41e21983ce) 
- [NER-Babelfy 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/63ce144889010406cdba5945cfcf382d93b520f3) 
- [NER-Babelfy 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/0d56ea462aae1bf173be52255848973db49e7891) 
- [NER-Dandelion 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/77e2af974e8920f1f6c9740391855610b2d15d58) 
- [NER-DBpediaSpotlight 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/357991ed5d7577683fe1fbe5f2d556b1445a1acd) 
- [NER-EntityClassifier 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/7ab34c9ac7d02cbda151f0d1cef5f8059f282f4e) 
- [NER-EntityClassifier2 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/10220a3c48c0ce63e04265d530b81a284295ecac) 
- [NER-Fox 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/8d25b0db16490c13af93987b8cd1c71ca1c2e42f) 
- [NER-MeaningCloud 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/a1bd6afc9f0dd3c8ddddea6b51f111298c657cee) 
- [NER-Ontotext 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/abc294f067213ed5f486ae2b930204fa68cd543d) 
- [NER-Stanford 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/8e01f5b2f967cf88467f4eff3cdb3b15857e1f90) 
- [NER-Tagme 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/a5a5cfa35bcfec1692d9da6ba3abce2dc8620084) 
- [NER-TextRazor 3.1.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/43c11c9ed1ec585d7cfef8c4f4b9bd125f4fbfd0) 
- [NERD-Alchemy 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/06119700a6eabc8a036cecf32db68fbd46a674a3) 
- [NERD-LuceneLinker 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/b9389773aada0c22945163bab96ba29dda7786ef) 
- [NERD-SMAPH 3.1.3](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/df01e1f75a1b6c7f9076f332d4a11d875ad669f0) 
- [QB-AnnotationOfSpotClass-OKBQA 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/1e66c5437f811c338614134071bf821c18c786b9) 
- [QB-BirthDataWikidata 3.2.9](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/e8c93502cbd7357696d03f977bea3b74fb02d82c) 
- [QB-ComicCharacterAlterEgoSimpleDBpedia 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/35124fae268846868d2157587faff3a51af704b4) 
- [QB-GAnswerWrapper 3.1.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/d466ef284dbf4b55322da50c9180e9fcba3b823b) 

**UPDATE 2**

- [removing qanary-component-REL-RelationLinker1 and qanary-component-RE…](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/5c92781b7b43155ed0c8953e6372319d96182b8c) 
- [removing qanary-component-REL-ReMatch: was only a dummy component](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/a41c3381b853a548fcc9f720d277bdc1b432d389)
- [QB-SimpleRealNameOfSuperHero 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/1b981bfce86ea74aba2ded4e6c5c92c503b51d0c)
- [QB-Sina 3.2.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/6dd63555d2c89b2c157509ed25ef3825cbd2c05a) 
- [QE-Wikidata 3.1.3](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/25b487889fec1c26f6a8ef5ad1c9ed2691b506bb) 
- [QB-PlatypusWrapper 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/233b9242be78a517f601be00d6c6288e95549806) 
- [QB-RuBQWrapper 3.1.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/315091a8fd308fe30effb745d05cfd36321c929d) 
- [QB-TeBaQAWrapper 3.1.6](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/e1c4f38d5db21ec0001eb9af1037c5babf5d6f15) 
- [QE-SparqlExecuter 3.1.6](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/74e07905da453cc9fca91587aedc1489da69e509) 
- [QBE-SimpleQueryBuilderAndExecutor 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/735c9f3f3e751bb2fd9613d1bdb7ea4dece25972) 
- [REL-RelNliod 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/48c9b21187c0a0adb537484b370833625125b432) 
- [QBE-SimpleQueryBuilderAndExecutor 3.1.3](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/b3bbde8ce11be46d75491c3ce8d00168a0b8f73b) 
- [NED-Aylien 4.1.6](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/c9ad34af54ecc770f4f92e877fb4950a0f67b320) 
- [NER-DBpediaSpotlight 3.1.3](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/eb2e7db61a9deb96438ab740ccb8a1e596af3c07) 
- [QE-SparqlExecuter 3.1.7](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/e6c27b7042d53b0a0b96ec1b380be82413a63688)

### CODE REVIEW

**Comment by caldoe** [comment]
@anbo-de 
I added some new Components, I didn't see that I should use `qanary.components` v3.7.0. 
I will use this version in for the next components.

New components:
- [NED-Dandelion 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/88c4ca477d9dd7cc0209ef3fdc074eccf593a2de) 
- [NED-DBpediaSpotlight 3.2.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/5e09abd1c76d3a0e5bcf91e072c91900131143a9) 
- [NED-DBpediaSpotlight 3.2.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/4c2ee925e8d25b5d1c9c93061d9eb0c1d7953f3c) 
- [NED DiambiguationClass OKBQA 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/dee2d507b3fec03873b5793592a98de68761aecd)

**Comment by anbo-de** [comment]
> @anbo-de I added some new Components, I didn't see that I should use `qanary.components` v3.7.0. I will use this version in for the next components.
> 
> New components:
> 
> * [NED-Dandelion 3.1.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/88c4ca477d9dd7cc0209ef3fdc074eccf593a2de)
> * [NED-DBpediaSpotlight 3.2.4](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/5e09abd1c76d3a0e5bcf91e072c91900131143a9)
> * [NED-DBpediaSpotlight 3.2.5](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/4c2ee925e8d25b5d1c9c93061d9eb0c1d7953f3c)
> * [NED DiambiguationClass OKBQA 3.1.2](https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/dee2d507b3fec03873b5793592a98de68761aecd)

@caldoe Sure, no worries. v3.7.0. is currently the latest version.

**Review by anbo-de — APPROVED** [review]
@caldoe very nice, thank you. I just added some small improvements.

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — APPROVED** [review]

**Review by anbo-de — COMMENTED** [review]
Qanary version was fixed in https://github.com/WDAqua/Qanary-question-answering-components/pull/247/commits/e6c27b7042d53b0a0b96ec1b380be82413a63688

**Review by anbo-de — APPROVED** [review]

**Comment by anbo-de** [comment]
@caldoe Thanks for updating all of these components.

**Pull request merged**
