### PR TITLE
Move common dependencies to qanary_component-parent

### PR DESCRIPTION
**Pull request by heinpa**
Resolves
#345 
#346 

Either remove dependencies entirely from individual POMs, or remove explicit versioning (if handled by DependencyManagement in qanary_component-parent)

### CODE REVIEW

**Comment by heinpa** [comment]
Qanary-component-QB-Sina was missing a throws declaration for `java.net.URISyntaxException` on method [`fetchEntities()`](https://github.com/WDAqua/Qanary-question-answering-components/blob/master/qanary-component-QB-Sina/src/main/java/eu/wdaqua/qanary/component/sina/qb/SINA.java#L112) that was causing a compilation error during the build process. As far as I can tell, this was not part of the original changes for this PR, and existed independently in the master branch.

**Comment by heinpa** [comment]
Also, test [`checkDetectedLanguageForQuestion()`](https://github.com/WDAqua/Qanary-question-answering-components/blob/master/qanary-component-LD-Shuyo/src/test/java/eu/wdaqua/qanary/component/shuyo/ld/LanguageDetectionTest.java#L134) for qanary-component-LD-Shuyo tends to fail because of insufficient detection quality, but will succeed when repeated. Maybe this should be re-evaluated in the context of automated testing deployment. 

```
Error:    LanguageDetectionTest.testGermanLanguages:134->checkDetectedLanguageForQuestion:162 Language detection quality not sufficient (83.33333333333334%). From 30 (de) questions only 25 were detected correctly. ==> expected: <true> but was: <false>
```

**Comment by anbo-de** [comment]
> Also, test [`checkDetectedLanguageForQuestion()`](https://github.com/WDAqua/Qanary-question-answering-components/blob/master/qanary-component-LD-Shuyo/src/test/java/eu/wdaqua/qanary/component/shuyo/ld/LanguageDetectionTest.java#L134) for qanary-component-LD-Shuyo tends to fail because of insufficient detection quality, but will succeed when repeated. Maybe this should be re-evaluated in the context of automated testing deployment.
> 
> ```
> Error:    LanguageDetectionTest.testGermanLanguages:134->checkDetectedLanguageForQuestion:162 Language detection quality not sufficient (83.33333333333334%). From 30 (de) questions only 25 were detected correctly. ==> expected: <true> but was: <false>
> ```

@heinpa Yes, the detection quality should stay constant with the embedded model. Unfortunately, it does not. I suggest reducing the threshold to 80 to overcome this problem hopefully once and for all: https://github.com/WDAqua/Qanary-question-answering-components/blob/master/qanary-component-LD-Shuyo/src/test/java/eu/wdaqua/qanary/component/shuyo/ld/LanguageDetectionTest.java#L28

**Comment by anbo-de** [comment]
:+1:

**Pull request merged**
