### PR TITLE
Qanary libretranslate python component

### PR DESCRIPTION
**Pull request by heinpa**

### CODE REVIEW

**Comment by Perevalov** [comment]
When running the current configuration with docker-compose, I'm getting the following error:

```
libretranslate_1  | Traceback (most recent call last):
libretranslate_1  |   File "/app/./venv/bin/libretranslate", line 33, in <module>
libretranslate_1  |     sys.exit(load_entry_point('libretranslate==1.3.9', 'console_scripts', 'libretranslate')())
libretranslate_1  |   File "/app/./venv/bin/libretranslate", line 25, in importlib_load_entry_point
libretranslate_1  |     return next(matches).load()
libretranslate_1  |   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
libretranslate_1  |     module = import_module(match.group('module'))
libretranslate_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
libretranslate_1  |     return _bootstrap._gcd_import(name[level:], package, level)
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
libretranslate_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
libretranslate_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/libretranslate/__init__.py", line 2, in <module>
libretranslate_1  |     from .main import main
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/libretranslate/main.py", line 5, in <module>
libretranslate_1  |     from libretranslate.app import create_app
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/libretranslate/app.py", line 10, in <module>
libretranslate_1  |     import argostranslatefiles
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslatefiles/__init__.py", line 1, in <module>
libretranslate_1  |     from argostranslatefiles.argostranslatefiles import *
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslatefiles/argostranslatefiles.py", line 1, in <module>
libretranslate_1  |     from argostranslate.translate import ITranslation
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslate/translate.py", line 8, in <module>
libretranslate_1  |     from argostranslate import apis, fewshot, package, sbd, settings
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslate/package.py", line 11, in <module>
libretranslate_1  |     from argostranslate import networking, settings
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslate/networking.py", line 6, in <module>
libretranslate_1  |     from argostranslate.utils import error, info
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslate/utils.py", line 4, in <module>
libretranslate_1  |     from argostranslate import settings
libretranslate_1  |   File "/app/venv/lib/python3.10/site-packages/argostranslate/settings.py", line 32, in <module>
libretranslate_1  |     os.makedirs(cache_dir, exist_ok=True)
libretranslate_1  |   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
libretranslate_1  |     mkdir(name, mode)
libretranslate_1  | PermissionError: [Errno 13] Permission denied: '/home/libretranslate/.local/cache/argos-translate'

```

@heinpa Could you check on your machine?

**Comment by Perevalov** [comment]
@heinpa Was it possible to reproduce the error I described above?

**Comment by heinpa** [comment]
@Perevalov the docker-compose file uses volumes to cache models. Is the location on the host machine accessible, i.e. do the permissions allow reading/writing?

**Comment by Perevalov** [comment]
> @Perevalov the docker-compose file uses volumes to cache models. Is the location on the host machine accessible (i.e. read/write permissions)?

Thanks, I figured it out.

**Pull request merged**
