### PR TITLE
Refactor Python Helsinki MT component

### PR DESCRIPTION
**Pull request by heinpa**
Add unit test for basic component functionality

### CODE REVIEW

**Review by Perevalov — COMMENTED** [review]
@heinpa I have one question regarding the `pytest.ini` as there are old config parameters from the Webengineering server: did you try to check it on the HTWK server (when it's available)?

**Comment by heinpa** [comment]
@Perevalov I took the config parameters that were used in `README.md`. 

I now updated `pytest.ini` to use `http://localhost`, as there are no live API connections that are part of the tests. The parameters are only necessary to initialize the component.
 
This also means that the availability on the specific server is currently not covered by the tests. They are only meant to check the basic functionality of this component.

**Comment by anbo-de** [comment]
@Perevalov Did you review the changes?

**Review by Perevalov — APPROVED** [review]
Looks good, as was mentioned -- webengineering sever @ HSA may confuse users.

**Comment by Perevalov** [comment]
@heinpa @anbo-de I approved the latest commit. Any of you can now merge it

**Pull request merged**
