### PR TITLE
QB-BirthDataWikidata 3.2.1

### PR DESCRIPTION
**Pull request by caldoe**
- update queries
- move query to separate file
- add new questions pattern
- remove some typos
- add the first and lastname annotation support

### CODE REVIEW

**Review by anbo-de — CHANGES_REQUESTED** [review]
@caldoe Please see the todos in the code.

**Comment by anbo-de** [comment]
@caldoe I improved the implementation. Please see my changes.

**Comment by caldoe** [comment]
@anbo-de 

looks good to me

**Review by anbo-de — APPROVED** [review]

**Comment by anbo-de** [comment]
@caldoe Thank you! :+1:

**Pull request merged**
