### PR TITLE
Update QBE QAnswer component

### PR DESCRIPTION
**Pull request by heinpa**
Implement changes that were already made for the related QB QAnswer component, mainly adding the required `user` parameter.

Annotate the QAnswer GERBIL result as JSON.

### CODE REVIEW

**Comment by anbo-de** [comment]
@heinpa Please change the component version (pom.xml) and reactivate the pull request.

**Comment by heinpa** [comment]
@heinpa add a flag to enable/disable unit tests with live endpoints

**Comment by heinpa** [comment]
@anbo-de 
please review the new PR: https://github.com/WDAqua/Qanary-question-answering-components/pull/272

**Comment by anbo-de** [comment]
@heinpa What about this merge request?

**Pull request merged**
